# This name 'build-check' is used with GitHub branch rules. Please do not change it!
name: "build-check"

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout repository

      - name: Build Docker image
        run: docker build -t chatterpay-front .
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          state: 'success'
