name: build-check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t chatterpay-front .

      - name: Report status check
        uses: actions/github-script@v6
        with:
          script: |
            const context = require('@actions/github').context;
            const { owner, repo } = context.repo;
            const sha = context.payload.pull_request.head.sha;
            const status = process.env.GITHUB_RUN_ID === undefined ? 'success' : 'failure';  // Set status based on build results
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: status,
              context: 'build-check',  // This is the name of the status check
              description: 'Docker Build Check'
            });