# This name 'build-check' is used with GitHub branch rules. Please do not change it!
name: "build-check"

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: echo "hola" # docker build -t chatterpay-front .
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Check Status Report'
          description: 'Check Status Report'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          state: 'success'
